"""Creacion de todas las tablas

Revision ID: 961708a58f94
Revises: 
Create Date: 2026-08-12 20:08:52.697625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961708a58f94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_cargo'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_cargos_id_cargo'), 'cargos', ['id_cargo'], unique=False)
    op.create_table('direcciones',
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('calle_av', sa.String(length=100), nullable=False),
    sa.Column('edificio_casa', sa.String(length=50), nullable=True),
    sa.Column('urbanizacion', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=50), nullable=False),
    sa.Column('municipio', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_index(op.f('ix_direcciones_id_direccion'), 'direcciones', ['id_direccion'], unique=False)
    op.create_table('estado_beneficiaria',
    sa.Column('id_estado_beneficiaria', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_estado_beneficiaria'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_estado_beneficiaria_id_estado_beneficiaria'), 'estado_beneficiaria', ['id_estado_beneficiaria'], unique=False)
    op.create_table('parentescos',
    sa.Column('id_parentesco', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_parentesco'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_parentescos_id_parentesco'), 'parentescos', ['id_parentesco'], unique=False)
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('expedientes',
    sa.Column('id_expediente', sa.Integer(), nullable=False),
    sa.Column('codigo_expediente', sa.String(length=20), nullable=False),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id_direccion'], ),
    sa.PrimaryKeyConstraint('id_expediente'),
    sa.UniqueConstraint('codigo_expediente')
    )
    op.create_index(op.f('ix_expedientes_id_expediente'), 'expedientes', ['id_expediente'], unique=False)
    op.create_table('instituciones',
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id_direccion'], ),
    sa.PrimaryKeyConstraint('id_institucion')
    )
    op.create_index(op.f('ix_instituciones_id_institucion'), 'instituciones', ['id_institucion'], unique=False)
    op.create_table('personal',
    sa.Column('id_personal', sa.Integer(), nullable=False),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=15), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo_personal', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id_cargo'], ),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id_direccion'], ),
    sa.PrimaryKeyConstraint('id_personal'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_personal_id_personal'), 'personal', ['id_personal'], unique=False)
    op.create_table('representantes',
    sa.Column('id_representante', sa.Integer(), nullable=False),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=False),
    sa.Column('ocupacion_laboral', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id_direccion'], ),
    sa.PrimaryKeyConstraint('id_representante')
    )
    op.create_index(op.f('ix_representantes_id_representante'), 'representantes', ['id_representante'], unique=False)
    op.create_table('beneficiarias',
    sa.Column('id_beneficiaria', sa.Integer(), nullable=False),
    sa.Column('id_expediente', sa.Integer(), nullable=False),
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.Column('id_direccion_lugar_nacimiento', sa.Integer(), nullable=False),
    sa.Column('id_estado_beneficiaria', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cedula_identidad', sa.String(length=15), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('grado_actual', sa.String(length=50), nullable=True),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_direccion_lugar_nacimiento'], ['direcciones.id_direccion'], ),
    sa.ForeignKeyConstraint(['id_estado_beneficiaria'], ['estado_beneficiaria.id_estado_beneficiaria'], ),
    sa.ForeignKeyConstraint(['id_expediente'], ['expedientes.id_expediente'], ),
    sa.ForeignKeyConstraint(['id_institucion'], ['instituciones.id_institucion'], ),
    sa.PrimaryKeyConstraint('id_beneficiaria')
    )
    op.create_index(op.f('ix_beneficiarias_id_beneficiaria'), 'beneficiarias', ['id_beneficiaria'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_personal', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_personal'], ['personal.id_personal'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_personal'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('beneficiaria_representante',
    sa.Column('id_beneficiaria', sa.Integer(), nullable=False),
    sa.Column('id_representante', sa.Integer(), nullable=False),
    sa.Column('id_parentesco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_beneficiaria'], ['beneficiarias.id_beneficiaria'], ),
    sa.ForeignKeyConstraint(['id_parentesco'], ['parentescos.id_parentesco'], ),
    sa.ForeignKeyConstraint(['id_representante'], ['representantes.id_representante'], ),
    sa.PrimaryKeyConstraint('id_beneficiaria', 'id_representante')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiaria_representante')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_beneficiarias_id_beneficiaria'), table_name='beneficiarias')
    op.drop_table('beneficiarias')
    op.drop_index(op.f('ix_representantes_id_representante'), table_name='representantes')
    op.drop_table('representantes')
    op.drop_index(op.f('ix_personal_id_personal'), table_name='personal')
    op.drop_table('personal')
    op.drop_index(op.f('ix_instituciones_id_institucion'), table_name='instituciones')
    op.drop_table('instituciones')
    op.drop_index(op.f('ix_expedientes_id_expediente'), table_name='expedientes')
    op.drop_table('expedientes')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_parentescos_id_parentesco'), table_name='parentescos')
    op.drop_table('parentescos')
    op.drop_index(op.f('ix_estado_beneficiaria_id_estado_beneficiaria'), table_name='estado_beneficiaria')
    op.drop_table('estado_beneficiaria')
    op.drop_index(op.f('ix_direcciones_id_direccion'), table_name='direcciones')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_cargos_id_cargo'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
