"""rename_personal_and_usuario_columns

Revision ID: c4abe5291984
Revises: 5126f6362921
Create Date: 2026-08-28 13:01:37.943379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4abe5291984'
down_revision: Union[str, None] = '5126f6362921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rename columns in personal table
    op.alter_column('personal', 'id_personal', new_column_name='id')
    op.alter_column('personal', 'nombres', new_column_name='nombre')
    op.alter_column('personal', 'apellidos', new_column_name='apellido')

    # Rename columns in usuarios table
    op.alter_column('usuarios', 'id_usuario', new_column_name='id')
    op.alter_column('usuarios', 'id_personal', new_column_name='personal_id')
    op.alter_column('usuarios', 'nombre_usuario', new_column_name='email', type_=sa.String(length=100))

    # Adjust indexes
    op.drop_index('ix_personal_id_personal', table_name='personal')
    op.create_index(op.f('ix_personal_id'), 'personal', ['id'], unique=False)
    op.drop_index('ix_usuarios_id_usuario', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('id_personal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('usuarios', sa.Column('nombre_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key('usuarios_id_personal_fkey', 'usuarios', 'personal', ['id_personal'], ['id_personal'])
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.create_unique_constraint('usuarios_nombre_usuario_key', 'usuarios', ['nombre_usuario'])
    op.create_unique_constraint('usuarios_id_personal_key', 'usuarios', ['id_personal'])
    op.create_index('ix_usuarios_id_usuario', 'usuarios', ['id_usuario'], unique=False)
    op.drop_column('usuarios', 'email')
    op.drop_column('usuarios', 'personal_id')
    op.drop_column('usuarios', 'id')
    op.add_column('personal', sa.Column('id_personal', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('personal', sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('personal', sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_personal_id'), table_name='personal')
    op.create_index('ix_personal_id_personal', 'personal', ['id_personal'], unique=False)
    op.drop_column('personal', 'apellido')
    op.drop_column('personal', 'nombre')
    op.drop_column('personal', 'id')
    # ### end Alembic commands ###
