from .direccion import Direccion
from .institucion import Institucion
from .estado_beneficiaria import EstadoBeneficiaria
from .parentesco import Parentesco
from .cargo import Cargo
from .rol import Rol
from .expediente import Expediente
from .beneficiaria import Beneficiaria
from .representante import Representante
from .beneficiaria_representante import BeneficiariaRepresentante
from .personal import Personal
from .usuario import Usuario